$:
  vscode:
    - docker:
        image: docker.cnb.cool/my-codespace/dev-image/tauri:latest
      services:
        - vscode
        - docker
      imports: https://cnb.cool/my-codespace/envs/-/blob/main/loemby-updater.yml

  push:
    - imports: https://cnb.cool/my-codespace/envs/-/blob/main/github-secret.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/NPCDW/WpfTool.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}
